# Node Timezone

Minimalist time library for Node.js and the browser.

## Synopsis

```javascript
var tz = require("tz").tz;

tz.timezones(require("/home/ignatius/zones/northamerica"));

y2k = tz("2000/01/01");
bicentenial = tz("1976/07/04", "America/Detroit");

// Accunts for leap year.
date = tz(bicentenial, "last year"); 

// Accunts for leap year and DST.
date = tz(bicentenial, "last January", "%c", "America/Detroit");
date = tz("now", "last January", "%c", "America/Detroit");
date = tz(new Date(), "last January", "%c", "America/Detroit");

// Getting tired of passing things around?
detroit = tz.curry("America/Detroit");
detroit("now", "%c");
hamtramck = detroit.curry("pl_PL");
```

Thus, `tz` always returns either milliseconds since the epoch in UTC, or a
formatted string if a format specifier is provided.
